from django.urls import path

from accounts.views import (
    AccountHomeView,
    AccountLogoutView,
    AuditLogListView,
    CharacterListView,
    EmailLoginView,
    ForgotPasswordCompleteView,
    ForgotPasswordConfirmView,
    ForgotPasswordDoneView,
    ForgotPasswordView,
    LanguagePreferenceView,
    OTServerCreateView,
    OTServerDeleteView,
    OTServerDetailView,
    OTServerListConnectionTestView,
    OTServerListView,
    OTServerUpdateView,
    PlatformSettingsView,
    RoleCreateView,
    RoleDeleteView,
    RoleDetailView,
    RoleManagementView,
    RoleUpdateView,
    SignUpView,
    TibiaVacationCreateView,
    TibiaVacationDeleteView,
    TibiaVacationListView,
    TibiaVacationUpdateView,
    UserCreateView,
    UserManagementView,
    UserToggleActiveView,
    UserUpdateView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", EmailLoginView.as_view(), name="login"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),
    path("language/", LanguagePreferenceView.as_view(), name="language"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="password_reset"),
    path(
        "forgot-password/done/",
        ForgotPasswordDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        ForgotPasswordConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        ForgotPasswordCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("home/", AccountHomeView.as_view(), name="home"),
    path("characters/", CharacterListView.as_view(), name="characters"),
    path("users/", UserManagementView.as_view(), name="users"),
    path("users/new/", UserCreateView.as_view(), name="user_create"),
    path("users/<str:pk>/edit/", UserUpdateView.as_view(), name="user_update"),
    path(
        "users/<str:pk>/toggle-active/",
        UserToggleActiveView.as_view(),
        name="user_toggle_active",
    ),
    path("roles/", RoleManagementView.as_view(), name="roles"),
    path("roles/new/", RoleCreateView.as_view(), name="role_create"),
    path("roles/<int:pk>/", RoleDetailView.as_view(), name="role_detail"),
    path("roles/<int:pk>/edit/", RoleUpdateView.as_view(), name="role_update"),
    path("roles/<int:pk>/delete/", RoleDeleteView.as_view(), name="role_delete"),
    path("otservers/", OTServerListView.as_view(), name="otservers"),
    path(
        "otservers/<int:pk>/test-connection/",
        OTServerListConnectionTestView.as_view(),
        name="otserver_test_connection",
    ),
    path("otservers/new/", OTServerCreateView.as_view(), name="otserver_create"),
    path("otservers/<int:pk>/", OTServerDetailView.as_view(), name="otserver_detail"),
    path(
        "otservers/vocations/", TibiaVacationListView.as_view(), name="tibia_vacations"
    ),
    path(
        "otservers/vocations/new/",
        TibiaVacationCreateView.as_view(),
        name="tibia_vacation_create",
    ),
    path(
        "otservers/vocations/<int:pk>/edit/",
        TibiaVacationUpdateView.as_view(),
        name="tibia_vacation_update",
    ),
    path(
        "otservers/vocations/<int:pk>/delete/",
        TibiaVacationDeleteView.as_view(),
        name="tibia_vacation_delete",
    ),
    path(
        "otservers/<int:pk>/edit/",
        OTServerUpdateView.as_view(),
        name="otserver_update",
    ),
    path(
        "otservers/<int:pk>/delete/",
        OTServerDeleteView.as_view(),
        name="otserver_delete",
    ),
    path(
        "settings/",
        PlatformSettingsView.as_view(),
        name="platform_settings",
    ),
    path("audit/", AuditLogListView.as_view(), name="audit_logs"),
]
