FROM python:3.13-windowsservercore-ltsc2022

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN python -m pip install --upgrade pip; pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

EXPOSE 8000

ENTRYPOINT ["powershell", "-File", "C:\\app\\entrypoint.ps1"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
