# Generated by Django 5.2.3 on 2026-03-16 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seed_default_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(default="OTServ Control Panel", max_length=120),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("en", "English"), ("pt-br", "Portuguese (Brazil)")],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("default_timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "primary_color",
                    models.CharField(
                        default="#06b6d4",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use a valid hex color, e.g. #06b6d4.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform setting",
                "verbose_name_plural": "Platform settings",
            },
        ),
    ]
