# Generated by Django 6.0.3 on 2026-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_preferred_language_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Name"),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                        ],
                        default="production",
                        max_length=20,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "database_engine",
                    models.CharField(
                        choices=[("mysql", "MySQL"), ("mariadb", "MariaDB")],
                        default="mysql",
                        max_length=20,
                        verbose_name="Database engine",
                    ),
                ),
                (
                    "db_host",
                    models.CharField(max_length=255, verbose_name="Database host"),
                ),
                (
                    "db_port",
                    models.PositiveIntegerField(
                        default=3306, verbose_name="Database port"
                    ),
                ),
                (
                    "db_name",
                    models.CharField(max_length=128, verbose_name="Database name"),
                ),
                (
                    "db_user",
                    models.CharField(max_length=128, verbose_name="Database user"),
                ),
                (
                    "db_password",
                    models.CharField(max_length=255, verbose_name="Database password"),
                ),
                (
                    "db_charset",
                    models.CharField(
                        default="utf8mb4",
                        max_length=64,
                        verbose_name="Database charset",
                    ),
                ),
                (
                    "db_collation",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Database collation"
                    ),
                ),
                (
                    "db_use_ssl",
                    models.BooleanField(default=False, verbose_name="Use SSL"),
                ),
                (
                    "api_base_url",
                    models.URLField(blank=True, verbose_name="API base URL"),
                ),
                (
                    "api_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API token"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=64, verbose_name="Timezone"
                    ),
                ),
                (
                    "monitor_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Monitoring enabled"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "OTServer",
                "verbose_name_plural": "OTServers",
                "ordering": ["name"],
            },
        ),
    ]
