# Generated by Django 6.0.3 on 2026-03-17

from __future__ import annotations

import base64
import hashlib

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations

ENCRYPTION_PREFIX = "enc::"


def _build_fernet() -> Fernet:
    secret_source = (
        getattr(settings, "OTSERVER_SECRETS_KEY", "") or settings.SECRET_KEY
    ).encode("utf-8")
    digest = hashlib.sha256(secret_source).digest()
    fernet_key = base64.urlsafe_b64encode(digest)
    return Fernet(fernet_key)


def _encrypt_if_needed(value: str) -> str:
    if not value or value.startswith(ENCRYPTION_PREFIX):
        return value
    token = _build_fernet().encrypt(value.encode("utf-8")).decode("utf-8")
    return f"{ENCRYPTION_PREFIX}{token}"


def encrypt_existing_otserver_secrets(apps, schema_editor):
    del schema_editor
    OTServer = apps.get_model("accounts", "OTServer")
    for server in OTServer.objects.all():
        new_db_password = _encrypt_if_needed(server.db_password)
        new_api_token = _encrypt_if_needed(server.api_token)
        if new_db_password != server.db_password or new_api_token != server.api_token:
            server.db_password = new_db_password
            server.api_token = new_api_token
            server.save(update_fields=["db_password", "api_token"])


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_otserver"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_otserver_secrets, noop_reverse),
    ]
