# Generated by Django 6.0.3 on 2026-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_encrypt_otserver_secrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otserver",
            name="api_token",
            field=models.TextField(blank=True, verbose_name="API token"),
        ),
        migrations.AlterField(
            model_name="otserver",
            name="db_password",
            field=models.TextField(verbose_name="Database password"),
        ),
    ]
