# Generated by Django 6.0.3 on 2026-03-18 13:00

import django.db.models.deletion
from django.db import migrations, models


def seed_default_tibia_vacations(apps, schema_editor):
    del schema_editor
    TibiaVacation = apps.get_model("accounts", "TibiaVacation")
    TibiaVersion = apps.get_model("accounts", "TibiaVersion")

    version_code = "15.30"
    if not TibiaVersion.objects.filter(code=version_code).exists():
        return

    rows = [
        (0, "None", "none", "Sem vocação", "sem vocação", 0, 0, 0),
        (1, "Sorcerer", "a sorcerer", "Feiticeiro", "um feiticeiro", 1, 1, 3),
        (2, "Druid", "a druid", "Druida", "um druida", 2, 2, 4),
        (3, "Paladin", "a paladin", "Paladino", "um paladino", 3, 3, 2),
        (4, "Knight", "a knight", "Cavaleiro", "um cavaleiro", 4, 4, 1),
        (
            5,
            "Master Sorcerer",
            "a master sorcerer",
            "Mestre Feiticeiro",
            "um mestre feiticeiro",
            1,
            1,
            13,
        ),
        (
            6,
            "Elder Druid",
            "an elder druid",
            "Ancião Druida",
            "um ancião druida",
            2,
            2,
            14,
        ),
        (
            7,
            "Royal Paladin",
            "a royal paladin",
            "Paladino Real",
            "um paladino real",
            3,
            3,
            12,
        ),
        (
            8,
            "Elite Knight",
            "an elite knight",
            "Cavaleiro de Elite",
            "um cavaleiro de elite",
            4,
            4,
            11,
        ),
        (9, "Monk", "an monk", "Monge", "um monge", 5, 9, 5),
        (
            10,
            "Exalted Monk",
            "an exalted monk",
            "Monge Exaltado",
            "um monge exaltado",
            5,
            9,
            15,
        ),
    ]

    for (
        vocation_id,
        name,
        description,
        name_pt_br,
        description_pt_br,
        base_id,
        from_voc,
        client_id,
    ) in rows:
        TibiaVacation.objects.update_or_create(
            tibia_version_id=version_code,
            vocation_id=vocation_id,
            defaults={
                "name": name,
                "description": description,
                "name_pt_br": name_pt_br,
                "description_pt_br": description_pt_br,
                "base_id": base_id,
                "from_voc": from_voc,
                "client_id": client_id,
            },
        )


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_otserver_tibia_version_fk_finalize"),
    ]

    operations = [
        migrations.CreateModel(
            name="TibiaVacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vocation_id",
                    models.PositiveSmallIntegerField(verbose_name="Vocation ID"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "name_pt_br",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Name (Portuguese)"
                    ),
                ),
                (
                    "description_pt_br",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Description (Portuguese)",
                    ),
                ),
                (
                    "base_id",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Base ID"),
                ),
                (
                    "from_voc",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="From vocation"
                    ),
                ),
                (
                    "client_id",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Client ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "tibia_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tibia_vacations",
                        to="accounts.tibiaversion",
                        verbose_name="Tibia version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tibia vacation",
                "verbose_name_plural": "Tibia vacations",
                "db_table": "tibia_vacations",
                "ordering": ["tibia_version_id", "vocation_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tibia_version", "vocation_id"),
                        name="uniq_tibia_vacation_per_version",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_default_tibia_vacations, noop_reverse),
    ]
