# Generated by Django 6.0.3 on 2026-03-18 14:47

import django.db.models.deletion
from django.db import migrations, models


def migrate_global_vacations_to_otservers(apps, schema_editor):
    del schema_editor
    OTServer = apps.get_model("accounts", "OTServer")
    TibiaVacation = apps.get_model("accounts", "TibiaVacation")

    global_rows = list(TibiaVacation.objects.filter(otserver__isnull=True))
    if not global_rows:
        return

    servers_by_version: dict[str, list] = {}
    for server in OTServer.objects.all():
        servers_by_version.setdefault(str(server.tibia_version_id), []).append(server)

    for row in global_rows:
        version_servers = servers_by_version.get(str(row.tibia_version_id), [])
        for server in version_servers:
            TibiaVacation.objects.update_or_create(
                otserver_id=server.pk,
                vocation_id=row.vocation_id,
                defaults={
                    "tibia_version_id": row.tibia_version_id,
                    "name": row.name,
                    "description": row.description,
                    "name_pt_br": row.name_pt_br,
                    "description_pt_br": row.description_pt_br,
                    "base_id": row.base_id,
                    "from_voc": row.from_voc,
                    "client_id": row.client_id,
                },
            )


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_tibiavacation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tibiavacation",
            options={
                "ordering": ["otserver_id", "vocation_id"],
                "verbose_name": "Tibia vacation",
                "verbose_name_plural": "Tibia vacations",
            },
        ),
        migrations.RemoveConstraint(
            model_name="tibiavacation",
            name="uniq_tibia_vacation_per_version",
        ),
        migrations.AddField(
            model_name="tibiavacation",
            name="otserver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vocations",
                to="accounts.otserver",
                verbose_name="OTServer",
            ),
        ),
        migrations.RunPython(migrate_global_vacations_to_otservers, noop_reverse),
        migrations.AddConstraint(
            model_name="tibiavacation",
            constraint=models.UniqueConstraint(
                fields=("otserver", "vocation_id"),
                name="uniq_tibia_vacation_per_otserver",
            ),
        ),
    ]
