# Generated by Django 6.0.3 on 2026-03-18 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_tibiavacation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otserver",
            name="last_health_check_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last health check at"
            ),
        ),
        migrations.AddField(
            model_name="otserver",
            name="last_health_check_message",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last health check message"
            ),
        ),
        migrations.AddField(
            model_name="otserver",
            name="last_health_check_ok",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Last health check successful"
            ),
        ),
        migrations.AddField(
            model_name="otserver",
            name="monitor_interval_minutes",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
                verbose_name="Monitoring interval (minutes)",
            ),
        ),
    ]
