# Generated by Django 6.0.3 on 2026-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_otserver_last_health_check_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otserver",
            name="schema_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional manual mapping for table and column names.",
                verbose_name="Schema mapping",
            ),
        ),
    ]
