name: Docker Build Linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Linux image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.linux
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/otserver-tibia-site:linux-${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/otserver-tibia-site:latest-linux
