name: Docker Build Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Windows image
        shell: pwsh
        run: |
          docker build -f Dockerfile.windows -t "${{ secrets.DOCKERHUB_USERNAME }}/otserver-tibia-site:windows-${{ github.sha }}" -t "${{ secrets.DOCKERHUB_USERNAME }}/otserver-tibia-site:latest-windows" .

      - name: Push Windows image
        shell: pwsh
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/otserver-tibia-site:windows-${{ github.sha }}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/otserver-tibia-site:latest-windows"
